### ISSUE TITLE
Bot nao está mandando sinais no grupo do telegram.

### ISSUE THREAD

**Issue by RafaelBaccarin** [jocimarjsc/blaze#2]
Executei o bot e ele nao esta mandando sinais no grupo do telegram, ja configurei ele com os padroes, tudo certinho, porem ele nao manda os sinais.

**Comment by jocimarjsc** [comment]
> Executei o bot e ele nao esta mandando sinais no grupo do telegram, ja configurei ele com os padroes, tudo certinho, porem ele nao manda os sinais.

Bom dia,

O bot só envia o sinal quando ele recebe a cor, ele é uma api que aguarda receber em uma  rota essa cor para que ele verifique se o padrão bateu, para assim poder enviar o sinal. 

Se você fizer um teste com o insomnia ou postman, você vai ver que o bot envia o sinal no telegram.
